### ISSUE TITLE
Can we have a python 3.7 build of this package

### ISSUE THREAD

**Issue by ouyangw** [conda-forge/flask-restful-feedstock#4]
There is no code related issue here but rather a build request. I’m not sure where to place this request so please let me know if I need to submit the request somewhere else. Thanks a lot for making conda-forge great!

**Comment by hajapy** [comment]
@ouyangw noarch builds have been available over a year now, please close the issue.

**Comment by wenjuno** [comment]
Sorry I haven't been following up, closing now. Thanks.
